### ISSUE TITLE
Me connecter à l'application

### ISSUE THREAD

**Issue by joe67100** [PTT-Alcatel/frontend#30]
**Objectif : être capable de se connecter à l'application à l'aide de ses identifiants rainbow**

- Le SDK Rainbow doit être initialisé (voir https://github.com/PTT-Alcatel/frontend/issues/29)
- Création d'une classe RainbowService qui va interagir avec Kotlin lorsque l'utilisateur entrera des informations dans l'UI

**Comment by bastianfbr** [comment]
Merged #31
