### ISSUE TITLE
Demander permission (GPS/Bluetooth)

### ISSUE THREAD

**Issue by bastianfbr** [PTT-Alcatel/frontend#40]
Il faut vérifier et demander les permissions Android pour le GPS et le Bluetooth.

**Liens utiles**

[Package Flutter](https://pub.dev/packages/permission_handler)
[Tutoriel](https://www.scaler.com/topics/permission-handler-flutter/)

**Comment by bastianfbr** [comment]
Permissions bluetooth OK (selon @max1lock)

**Comment by max1lock** [comment]
Permissions GPS OK (branche 36)
